<div id="secondary"> 
  <div class="top"></div> 
  <div class="body"> 
    <div class="title_bg"> 
      <div class="title">News Feeds</div> 
    </div> 
    <div class="story">&nbsp;&nbsp;&middot; <a href="?feed=main">Main </a><br> 
        &nbsp;&nbsp;&middot; <a href="?feed=dev">Development Feed</a><br> 
        &nbsp;&nbsp;&middot; <a href="?feed=musou">Musou's Diary</a><br> 
        &nbsp;&nbsp;&middot; <a href="?feed=iver">Iver's Diary</a></div> 
	<div class="footer"></div>
  </div> 
  <div class="bottom"></div> 
  <br>
    <div class="top"></div> 
  <div class="body"> 
    <div class="title_bg"> 
      <div class="title">Join Us</div> 
    </div> 
    <div class="story">Click here to join us.</div> 
	<div class="footer"></div>
  </div> 
  <div class="bottom"></div> 
  <br>
    <div class="top"></div> 
  <div class="body"> 
    <div class="title_bg"> 
      <div class="title">Current Crews</div> 
    </div> 
    <div class="story">Rank 1: The Northpark Allstars (C. Iver) <br> 
        Rank 2: The Northpark Gangsters (C. Musou) <br> 
        Rank 3: The Northpark Assassins (C. Kathaya)</div> 
	<div class="footer"></div>
  </div> 
  <div class="bottom"></div> 
  <br>
</div>
